import fs from 'fs';
import path from 'path';

export default async function Dashboard() {
  // Locate and read the report data generated by your backend tool
  const filePath = path.join(process.cwd(), 'report.json');
  
  if (!fs.existsSync(filePath)) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-zinc-50 dark:bg-black p-10 font-sans">
        <div className="text-center p-8 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm">
          <h1 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">No report data found</h1>
          <p className="text-sm text-zinc-500 mt-2">Please run your backend pipeline tool first to generate report.json.</p>
        </div>
      </main>
    );
  }

  const fileData = fs.readFileSync(filePath, 'utf-8');
  const report = JSON.parse(fileData);

  return (
    <main className="min-h-screen bg-zinc-50 dark:bg-black p-8 font-sans">
      <div className="max-w-4xl mx-auto">
        <header className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">Reporting Dashboard</h1>
          <p className="text-zinc-500 mt-1">This dashboard visualises the sales data and conversion rates for my uni work-based project.</p>
        </header>

        {/* KPI Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          
          {/* Conversion Rate Card */}
          <div className="p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm">
            <h2 className="text-sm font-medium text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">Conversion Rate</h2>
            <div className="flex items-baseline gap-2 mt-4">
              <span className="text-5xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
                {report.conversionRate}%
              </span>
            </div>
            <p className="text-xs text-zinc-400 mt-2">
              Based on {report.wonOpportunities} won out of {report.totalOpportunities} total opportunities.
            </p>
          </div>

          {/* Total Pipeline Value Card */}
          <div className="p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm">
            <h2 className="text-sm font-medium text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">Total Pipeline Value</h2>
            <div className="flex items-baseline gap-2 mt-4">
              <span className="text-5xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
                £{Number(report.totalPipelineValue).toLocaleString()}
              </span>
            </div>
            <p className="text-xs text-zinc-400 mt-2">
              Active projected value across all tracked lifecycle stages.
            </p>
          </div>

        </div>

        {/* Financial Context Banner */}
        <div className="p-4 bg-zinc-100 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 rounded-lg text-sm text-zinc-600 dark:text-zinc-400 mb-10">
          💼 <strong>Won Pipeline Contribution:</strong> £{Number(report.wonPipelineValue).toLocaleString()} has successfully transitioned to closed-won.
        </div>

        {/* Opportunities Table */}
        <div>
          <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-50 mb-4">All Opportunities</h2>
          <div className="overflow-hidden bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm">
            <table className="w-full text-left text-sm">
              <thead className="bg-zinc-50 dark:bg-zinc-950 border-b border-zinc-200 dark:border-zinc-800">
                <tr>
                  <th className="px-6 py-4 font-semibold text-zinc-900 dark:text-zinc-50">Company</th>
                  <th className="px-6 py-4 font-semibold text-zinc-900 dark:text-zinc-50">Stage</th>
                  <th className="px-6 py-4 font-semibold text-zinc-900 dark:text-zinc-50">Value</th>
                  <th className="px-6 py-4 font-semibold text-zinc-900 dark:text-zinc-50">Last Contact</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-200 dark:divide-zinc-800">
                {report.opportunities.map((opp: any) => (
                  <tr key={opp.id} className="hover:bg-zinc-50 dark:hover:bg-zinc-800/50">
                    <td className="px-6 py-4 font-medium text-zinc-900 dark:text-zinc-50">{opp.company}</td>
                    <td className="px-6 py-4 text-zinc-600 dark:text-zinc-400">{opp.stage}</td>
                    <td className="px-6 py-4 text-zinc-900 dark:text-zinc-50">£{opp.value.toLocaleString()}</td>
                    <td className="px-6 py-4 text-zinc-500">{opp.lastContact}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </main>
  );
}